# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\x05\x65mbed\"Q\n\x0c\x45mbedRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\"\"\n\rEmbedResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\x32N\n\x0c\x45mbedService\x12>\n\x11GenerateEmbedding\x12\x13.embed.EmbedRequest\x1a\x14.embed.EmbedResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDREQUEST']._serialized_start=26
  _globals['_EMBEDREQUEST']._serialized_end=107
  _globals['_EMBEDRESPONSE']._serialized_start=109
  _globals['_EMBEDRESPONSE']._serialized_end=143
  _globals['_EMBEDSERVICE']._serialized_start=145
  _globals['_EMBEDSERVICE']._serialized_end=223
# @@protoc_insertion_point(module_scope)
